//tag::ref-doc[]

= Frame Grabber Source

Reads a file or camera video stream, extracts single video frames as images and feeds them to the outbound binder.
You can configure the source location size of the output images and the frame grabbing interval.

If the `inputVideoUri` property is not empty the Frame Grabber will use it as input video source to grab frames.
If `inputVideoUri` is empty (default) then the Grabber will use the specified Webcam device as on input video stream source.

Powered by https://github.com/bytedeco/javacv[javaCV] (OpenCV java wrapper).

== Options

//tag::configuration-properties[]
$$frame.grabber.capture-interval$$:: $$Capture interval$$ *($$Long$$, default: `$$100$$`)*
$$frame.grabber.device-index$$:: $$When more than one webcams are presented use the camera index specifies which one to use.$$ *($$Integer$$, default: `$$0$$`)*
$$frame.grabber.height$$:: $$Capture height$$ *($$Integer$$, default: `$$144$$`)*
$$frame.grabber.input-video-uri$$:: $$Location of an input video file to grab frames from. Supports file:/ , http:// or , classpath:/ locations.
 If null the grabber will use the Webcams as input video stream$$ *($$Resource$$, default: `$$<none>$$`)*
$$frame.grabber.output-image-type$$:: $$Image type send as byte array$$ *($$ImageType$$, default: `$$<none>$$`, possible values: `RGB`,`ARGB`,`ARGB_PRE`,`BRG`,`BRG_3BYTE`,`BRG_4BYTE`,`BRG_PRE_4BYTE`,`USHORT_565_RGB`,`USHORT_555_RGB`,`BYTE_GRAY`,`USHORT_GRAY`,`BYTE_BINARY`,`BYTE_INDEXED`)*
$$frame.grabber.width$$:: $$Capture width$$ *($$Integer$$, default: `$$176$$`)*
//end::configuration-properties[]

//end::ref-doc[]

== Build

This is a two-stage process. First build the apps and generate the binder specific app starters projects:
```
$ ./mvnw clean install -PgenerateApps
```

You can find the corresponding binder based projects in the `apps`.

Cd into `apps` and build it:
```
$ cd apps
$ ./mvnw clean package
```

== Examples

Capture frames form Web cameras:
```
java -jar frame-grabber-source.jar --width=320 --height=240 --capture-interval=100
```

Read frames from input video file:
```
java -jar frame-grabber-source.jar --width=320 --height=240 --capture-interval=1 --input-video-uri='http://techslides.com/demos/sample-videos/small.mp4'
```


And here is a example SCDF pipeline that uses `image-viewer` to shows the grabbed images:

```
frame-grabber-stream=frame-grabber --width=320 --height=240 --capture-interval=100 | image-viewer
```

Example for grabbing image frames for an input video file (supports `file:/`, `http://` and `classpath:/` input locations)
```
video-file-stream=frame-grabber --width=640 --height=480 --capture-interval=1 --input-video-uri='http://techslides.com/demos/sample-videos/small.mp4' | image-viewer
```
